import json
import os
from datetime import datetime

def parse_checkov_report(report_path):
    if not os.path.exists(report_path):
        print(f"[ERROR] Report file not found: {report_path}")
        return ""

    with open(report_path, "r") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"[ERROR] Failed to parse JSON: {e}")
            return "# ❌ Invalid JSON generated by Checkov\n"

    if "results" not in data:
        return "# ✅ No issues found by Checkov.\n"

    output = "# 🚨 Checkov Scan Report\n"
    output += f"_Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_\n\n"

    results = data.get("results", {})
    failed_checks = results.get("failed_checks", [])

    if not failed_checks:
        return "# ✅ No failed checks found!\n"

    output += f"## ❌ {len(failed_checks)} Failed Checks\n\n"

    for check in failed_checks:
        output += f"### 🔎 {check.get('check_id')} - {check.get('check_name')}\n"
        output += f"- **Severity**: `{check.get('severity', 'UNKNOWN')}`\n"
        output += f"- **File**: `{check.get('file_path')}`\n"
        output += f"- **Resource**: `{check.get('resource')}`\n"
        output += f"- **Guideline**: {check.get('guideline') or 'N/A'}\n"
        output += f"- **Description**: {check.get('check_details') or 'No description'}\n\n"

    return output

if __name__ == "__main__":
    input_path = os.getenv("CHECKOV_JSON_PATH", "checkov_reports/report.json")
    markdown = parse_checkov_report(input_path)

    output_path = "checkov_reports/report.md"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(markdown)

    print(f"[✅] Markdown report generated at: {output_path}")
