on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  fix-s3:
    if: github.event.label.name == 'fix-s3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Fix Script
        run: python scripts/fix_s3_buckets.py
      - name: Commit fixes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🔒 Auto-fixed public S3 bucket ACLs"
          git push
